# Generated by Django 5.0.6 on 2024-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('companybusyo', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('furi1', models.CharField(max_length=100)),
                ('furi2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tell', models.CharField(max_length=20)),
                ('zip1', models.CharField(max_length=10)),
                ('zip2', models.CharField(max_length=10)),
                ('add', models.CharField(max_length=255)),
                ('add2', models.CharField(max_length=255)),
                ('etc', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': ('emails',),
                'managed': False,
            },
        ),
    ]
